// <auto-generated />
using System;
using MSVenta.Compras.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MSVenta.Compras.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    [Migration("20260620191310_AddAdquisicion")]
    partial class AddAdquisicion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MSVenta.Compras.Models.Adquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_adquisicion")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Glosa")
                        .HasColumnType("text")
                        .HasColumnName("glosa");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("id_orden");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("adquisicion");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.CatalogoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_catalogo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("StockDisponible")
                        .HasColumnType("numeric")
                        .HasColumnName("stock_disponible");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("catalogo_proveedor");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.DetalleAdquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_adq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdquisicionId")
                        .HasColumnType("integer")
                        .HasColumnName("id_adquisicion");

                    b.Property<int?>("AlmacenId")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioUni")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_uni");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.HasKey("Id");

                    b.HasIndex("AdquisicionId");

                    b.ToTable("detalle_adquisicion");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_compra")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<int>("CompraId")
                        .HasColumnType("integer")
                        .HasColumnName("id_compra");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioUni")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_uni");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("detalle_compra");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.DetalleOrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_orden")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_producto");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("id_orden");

                    b.Property<decimal>("PrecioUni")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_uni");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("detalle_orden_compra");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.NotaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_compra")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_compra");

                    b.Property<string>("Glosa")
                        .HasColumnType("text")
                        .HasColumnName("glosa");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("TipoPago")
                        .HasColumnType("text")
                        .HasColumnName("tipo_pago");

                    b.Property<decimal>("TotalCompra")
                        .HasColumnType("numeric")
                        .HasColumnName("total_compra");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("nota_compra");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_orden")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Glosa")
                        .HasColumnType("text")
                        .HasColumnName("glosa");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("orden_compra");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("proveedor");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.Adquisicion", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.OrdenCompra", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MSVenta.Compras.Models.Proveedor", "Proveedor")
                        .WithMany("Adquisiciones")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Orden");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.CatalogoProveedor", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.Proveedor", "Proveedor")
                        .WithMany("Catalogo")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.DetalleAdquisicion", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.Adquisicion", "Adquisicion")
                        .WithMany("Detalles")
                        .HasForeignKey("AdquisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adquisicion");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.DetalleCompra", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.NotaCompra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.DetalleOrdenCompra", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.OrdenCompra", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.NotaCompra", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.Proveedor", "Proveedor")
                        .WithMany("NotasCompra")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.OrdenCompra", b =>
                {
                    b.HasOne("MSVenta.Compras.Models.Proveedor", "Proveedor")
                        .WithMany("Ordenes")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.Adquisicion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.NotaCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("MSVenta.Compras.Models.Proveedor", b =>
                {
                    b.Navigation("Adquisiciones");

                    b.Navigation("Catalogo");

                    b.Navigation("NotasCompra");

                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
