-- public.proveedor definition
-- Drop table
-- DROP TABLE proveedor;

create table proveedor ( id_proveedor serial4 not null,
nombre varchar(150) not null,
telefono varchar(20) null,
email varchar(150) null,
direccion varchar(200) null,
nit varchar(20) null,
contacto varchar(100) null,
fecha_registro timestamp default CURRENT_TIMESTAMP null,
estado varchar(20) default 'activo'::character varying null,
constraint proveedor_pkey primary key (id_proveedor));
-- public.catalogo_proveedor definition
-- Drop table
-- DROP TABLE catalogo_proveedor;

create table catalogo_proveedor ( id_catalogo serial4 not null,
precio_unitario numeric(12, 2) not null,
stock_disponible numeric(10, 2) default 0 null,
estado varchar(20) default 'activo'::character varying null,
id_proveedor int4 null,
id_producto int4 null,
constraint catalogo_proveedor_pkey primary key (id_catalogo),
constraint catalogo_proveedor_id_proveedor_fkey foreign key (id_proveedor) references proveedor(id_proveedor));
-- public.nota_compra definition
-- Drop table
-- DROP TABLE nota_compra;

create table nota_compra ( id_compra serial4 not null,
fecha_compra date not null,
total_compra numeric(12, 2) default 0 null,
estado varchar(20) default 'activo'::character varying null,
glosa text null,
tipo_pago varchar(20) default 'contado'::character varying null,
id_proveedor int4 null,
id_usuario int4 null,
constraint nota_compra_pkey primary key (id_compra),
constraint nota_compra_id_proveedor_fkey foreign key (id_proveedor) references proveedor(id_proveedor));
-- public.orden_compra definition
-- Drop table
-- DROP TABLE orden_compra;

create table orden_compra ( id_orden int4 generated by default as identity( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle) not null,
fecha timestamp not null,
estado text null,
glosa text null,
total numeric not null,
id_proveedor int4 null,
id_usuario int4 null,
constraint "PK_orden_compra" primary key (id_orden),
constraint "FK_orden_compra_proveedor_id_proveedor" foreign key (id_proveedor) references proveedor(id_proveedor) on
delete
    restrict);

create index "IX_orden_compra_id_proveedor" on
public.orden_compra
    using btree (id_proveedor);
-- public.adquisicion definition
-- Drop table
-- DROP TABLE adquisicion;

create table adquisicion ( id_adquisicion int4 generated by default as identity( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle) not null,
fecha timestamp not null,
estado text null,
glosa text null,
id_orden int4 null,
id_proveedor int4 null,
id_usuario int4 null,
constraint "PK_adquisicion" primary key (id_adquisicion),
constraint "FK_adquisicion_orden_compra_id_orden" foreign key (id_orden) references orden_compra(id_orden) on
delete
    set
    null,
    constraint "FK_adquisicion_proveedor_id_proveedor" foreign key (id_proveedor) references proveedor(id_proveedor) on
    delete
        restrict);

create index "IX_adquisicion_id_orden" on
public.adquisicion
    using btree (id_orden);

create index "IX_adquisicion_id_proveedor" on
public.adquisicion
    using btree (id_proveedor);
-- public.detalle_adquisicion definition
-- Drop table
-- DROP TABLE detalle_adquisicion;

create table detalle_adquisicion ( id_detalle_adq int4 generated by default as identity( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle) not null,
cantidad numeric not null,
precio_uni numeric not null,
sub_total numeric not null,
nombre_producto text null,
id_adquisicion int4 not null,
id_producto int4 null,
id_almacen int4 null,
constraint "PK_detalle_adquisicion" primary key (id_detalle_adq),
constraint "FK_detalle_adquisicion_adquisicion_id_adquisicion" foreign key (id_adquisicion) references adquisicion(id_adquisicion) on
delete
    cascade);

create index "IX_detalle_adquisicion_id_adquisicion" on
public.detalle_adquisicion
    using btree (id_adquisicion);
-- public.detalle_compra definition
-- Drop table
-- DROP TABLE detalle_compra;

create table detalle_compra ( id_detalle_compra serial4 not null,
cantidad numeric(10, 2) not null,
precio_uni numeric(12, 2) not null,
sub_total numeric(12, 2) default 0 null,
nombre_producto varchar(200) null,
id_compra int4 null,
id_producto int4 null,
constraint detalle_compra_pkey primary key (id_detalle_compra),
constraint detalle_compra_id_compra_fkey foreign key (id_compra) references nota_compra(id_compra));
-- public.detalle_orden_compra definition
-- Drop table
-- DROP TABLE detalle_orden_compra;

create table detalle_orden_compra ( id_detalle_orden int4 generated by default as identity( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle) not null,
cantidad numeric not null,
precio_uni numeric not null,
sub_total numeric not null,
nombre_producto text null,
id_orden int4 not null,
id_producto int4 null,
constraint "PK_detalle_orden_compra" primary key (id_detalle_orden),
constraint "FK_detalle_orden_compra_orden_compra_id_orden" foreign key (id_orden) references orden_compra(id_orden) on
delete
    cascade);

create index "IX_detalle_orden_compra_id_orden" on
public.detalle_orden_compra
    using btree (id_orden);
