// <auto-generated />
using System;
using MSVenta.Inventario.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSVenta.Inventario.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    partial class ContextDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("MSVenta.Inventario.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadMax")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("almacen");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Id_Marca")
                        .HasColumnType("int");

                    b.Property<int>("Id_UnidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Categoria");

                    b.HasIndex("Id_Marca");

                    b.HasIndex("Id_UnidadMedida");

                    b.ToTable("articulo");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.ArticuloAlmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_Almacen")
                        .HasColumnType("int");

                    b.Property<int>("Id_Articulo")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMax")
                        .HasColumnType("int");

                    b.Property<int>("StockMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Almacen");

                    b.HasIndex("Id_Articulo");

                    b.ToTable("articulo_almacen");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.DetalleEgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_ArticuloAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("Id_Egreso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id_ArticuloAlmacen");

                    b.HasIndex("Id_Egreso");

                    b.ToTable("detalle_egreso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.DetalleIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_ArticuloAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("Id_Ingreso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id_ArticuloAlmacen");

                    b.HasIndex("Id_Ingreso");

                    b.ToTable("detalle_ingreso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.DetalleTraspaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_ArticuloAlmacen")
                        .HasColumnType("int");

                    b.Property<int>("Id_Traspaso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_ArticuloAlmacen");

                    b.HasIndex("Id_Traspaso");

                    b.ToTable("detalle_traspaso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Egreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Glosa")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("nota_egreso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.GesPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Articulo")
                        .HasColumnType("int");

                    b.Property<string>("MetodoInventario")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Articulo");

                    b.ToTable("ges_precio");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Glosa")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.Property<bool>("SoloRegistro")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("nota_ingreso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("marca");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Traspaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Glosa")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_AlmacenDestino")
                        .HasColumnType("int");

                    b.Property<int>("Id_AlmacenOrigen")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_AlmacenDestino");

                    b.HasIndex("Id_AlmacenOrigen");

                    b.ToTable("traspaso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("unidad_medida");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Articulo", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("Id_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("Id_Marca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("Id_UnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.ArticuloAlmacen", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("Id_Almacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("Id_Articulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.DetalleEgreso", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.ArticuloAlmacen", "ArticuloAlmacen")
                        .WithMany()
                        .HasForeignKey("Id_ArticuloAlmacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("Id_Egreso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticuloAlmacen");

                    b.Navigation("Egreso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.DetalleIngreso", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.ArticuloAlmacen", "ArticuloAlmacen")
                        .WithMany()
                        .HasForeignKey("Id_ArticuloAlmacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("Id_Ingreso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticuloAlmacen");

                    b.Navigation("Ingreso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.DetalleTraspaso", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.ArticuloAlmacen", "ArticuloAlmacen")
                        .WithMany()
                        .HasForeignKey("Id_ArticuloAlmacen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.Traspaso", "Traspaso")
                        .WithMany()
                        .HasForeignKey("Id_Traspaso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticuloAlmacen");

                    b.Navigation("Traspaso");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.GesPrecio", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("Id_Articulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("MSVenta.Inventario.Models.Traspaso", b =>
                {
                    b.HasOne("MSVenta.Inventario.Models.Almacen", "AlmacenDestino")
                        .WithMany()
                        .HasForeignKey("Id_AlmacenDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSVenta.Inventario.Models.Almacen", "AlmacenOrigen")
                        .WithMany()
                        .HasForeignKey("Id_AlmacenOrigen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlmacenDestino");

                    b.Navigation("AlmacenOrigen");
                });
#pragma warning restore 612, 618
        }
    }
}
